# Generated by Django 2.1.7 on 2019-03-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190309_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taliatext',
            name='content',
            field=models.CharField(max_length=140),
        ),
    ]
