# Generated by Django 2.0.6 on 2018-06-17 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['graphic', 'file']},
        ),
    ]
