# Generated by Django 2.0.6 on 2018-06-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0002_auto_20180617_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='graphics/js/%Y/%m/%d/'),
        ),
    ]
