# Generated by Django 2.0.6 on 2018-06-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0004_auto_20180617_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='graphics/None'),
        ),
    ]
