# Generated by Django 2.0.6 on 2018-06-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0005_auto_20180617_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='graphics/<django.db.models.fields.related.ForeignKey>'),
        ),
    ]
