# Generated by Django 2.0.6 on 2018-06-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0006_auto_20180617_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='graphics/<property object at 0x05DDC300>'),
        ),
    ]
