# Generated by Django 2.0.6 on 2018-06-20 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0008_auto_20180619_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ['file']},
        ),
    ]
