# Generated by Django 2.0.6 on 2018-06-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0009_auto_20180619_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='file',
            options={},
        ),
        migrations.AlterModelOptions(
            name='graphic',
            options={},
        ),
        migrations.RemoveField(
            model_name='graphic',
            name='image',
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='graphic',
            name='title',
            field=models.CharField(max_length=30),
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='graphic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='graphics.Graphic'),
        ),
    ]
