# Generated by Django 2.0.6 on 2018-06-24 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0011_auto_20180624_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='title',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
