# Generated by Django 2.0.6 on 2018-07-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0012_auto_20180624_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphic',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='graphic',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
