# Generated by Django 2.0.6 on 2018-07-12 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0013_auto_20180712_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphic',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
