# Generated by Django 2.0.6 on 2018-07-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0015_auto_20180712_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='file',
            name='primary',
        ),
    ]
