# Generated by Django 2.0.6 on 2018-07-17 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0016_auto_20180716_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='graphics.FileType'),
        ),
    ]
