# Generated by Django 2.0.6 on 2018-07-17 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0017_file_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filetype',
            options={'ordering': ['name']},
        ),
    ]
